START TRANSACTION;

DROP DATABASE IF EXISTS nicosophro_bdd;
CREATE DATABASE nicosophro_bdd;
USE nicosophro_bdd;

DROP TABLE IF EXISTS `contact`;
CREATE TABLE `contact` (
    `id` INT(10) NOT NULL AUTO_INCREMENT,
    `lastname` VARCHAR(255) NOT NULL,
    `firstname` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `content` VARCHAR(255) NOT NULL,
    `phone` VARCHAR(20) NOT NULL,
    `date_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `date_read` DATETIME,
    `read` BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (`id`)
)ENGINE=innoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
    `id` INT(10) NOT NULL AUTO_INCREMENT,
    `firstname` VARCHAR(100) NOT NULL,
    `lastname` VARCHAR(100) NOT NULL,
    `email` VARCHAR(100) NOT NULL UNIQUE,
    `address` VARCHAR(255) NOT NULL,
    `zip_code` VARCHAR(50) NOT NULL,
    `city` VARCHAR(50) NOT NULL,
    `date_birthday` DATETIME NOT NULL,
    `role` VARCHAR(100) NOT NULL,
    `phone` VARCHAR(20) NOT NULL UNIQUE,
    `date_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `active` BOOLEAN DEFAULT TRUE,
    `type` int,
    PRIMARY KEY (`id`)
)ENGINE=innoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;